apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: monitoring

labels:
  - includeSelectors: true
    pairs:
      stack: monitoring
      env: prod