apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-resources
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list"]
