apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: monitoring

labels:
  - includeSelectors: true
    pairs:
      stack: monitoring
      env: stage

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus/prometheus.yml
      - prometheus/rule.yml
  - name: alertmanager-config
    files:
      - alertmanager/alertmanager.yml
generatorOptions:
  disableNameSuffixHash: false
