apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base

namespace: monitoring

labels:
  - includeSelectors: true
    pairs:
      stack: monitoring
      env: stage

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus/prometheus.yml
      - prometheus/rule.yml
  - name: alertmanager-config
    files:
      - alertmanager/alertmanager.yml

secretGenerator:
  - name: alertmanager-msteams-secret
    envs:
      - secrets/msteams_webhook_url.env
  - name: alertmanager-slack-secret
    envs:
      - secrets/slack_oauth_token.env

# replacements:
#   - source:
#       kind: Secret
#       name: alertmanager-slack-secret
#       fieldPath: data.SLACK_NOTIFY_BOT_OAUTH_TOKEN
#     targets:
#       - select:
#           kind: ConfigMap
#           name: alertmanager-config  # your ConfigMap name containing alertmanager.yml
#         fieldPaths:
#           - data.alertmanager.yml     # path inside ConfigMap where you want to replace

