# ────────────────────────────────────────────────────────────────────────────────
# Issue a self-signed CA and server cert via cert-manager
# ────────────────────────────────────────────────────────────────────────────────
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bitwarden-sdk-ca
  namespace: external-secrets
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-sdk-ca
  namespace: external-secrets
spec:
  isCA: true
  secretName: bitwarden-ca-key-pair
  commonName: bitwarden-sdk-ca
  duration: 8760h
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: bitwarden-sdk-ca
    kind: Issuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-sdk-server-tls
  namespace: external-secrets
spec:
  secretName: bitwarden-tls-certs
  commonName: bitwarden-sdk-server.external-secrets.svc.cluster.local
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: bitwarden-sdk-ca
    kind: Issuer

# ---
# # argocd-apps/external-secrets-crds.yaml
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: external-secrets-crds
#   namespace: argocd
# spec:
#   project: infrastructure
#   source:
#     repoURL: https://github.com/external-secrets/external-secrets
#     targetRevision: v0.5.8
#     path: deploy/crds
#     directory:
#       recurse: true
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: external-secrets
#   syncPolicy:
#     automated:
#       prune: false       # don’t prune CRDs!
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: infrastructure

  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.17.0
    helm:
      values: |
        installCRDs: true

        bitwarden-sdk-server:
          enabled: true
          tls:
            enabled: true
            secretName: bitwarden-tls-certs

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/names
        - /spec/versions

---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            namespace: external-secrets
            key: token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      organizationID: 12c54d5e-9832-4680-a555-b1c400be0305
      projectID:      29cb27ba-e63a-48b8-b1f6-b2f400d746b2
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook-url
  namespace: external-secrets
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: teams-webhook-url
    creationPolicy: Owner
  data:
    - secretKey: slack-webhook-url
      remoteRef:
        key: slack-webhook-url
