apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.5.0/deploy/rbac-csi-nfs.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.5.0/deploy/csi-nfs-driverinfo.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.5.0/deploy/csi-nfs-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.5.0/deploy/csi-nfs-node.yaml
  - storage-class.yml
  - test-pvc.yml

labels:
  - includeSelectors: true
    pairs:
      stack: nfs-csi

# Create config map with server IP
configMapGenerator:
  - name: nfs-config
    literals:
      - NFS_SERVER=10.0.0.10
      - RECLAIM_POLICY=Retain

# Replace field parameters.server in storage class object with cm value
replacements:
  - source:
      kind: ConfigMap
      name: nfs-config
      fieldPath: data.NFS_SERVER
    targets:
      - select:
          kind: StorageClass
          name: nfs-csi
        fieldPaths:
          - parameters.server
  - source:
      kind: ConfigMap
      name: nfs-config
      fieldPath: data.RECLAIM_POLICY
    targets:
      - select:
          kind: StorageClass
          name: nfs-csi
        fieldPaths:
          - reclaimPolicy