apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - 'alertmanager.monitoring.svc:9093'

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

    # rule_files:
    #   - '/etc/prometheus/rule.yml'


  rule.yml: |