apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml  # Ensure namespace is created first

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version:  4.12.0 # Check for the latest version
    releaseName: nginx-ingress
    namespace: ingress-nginx
    valuesInline:
      controller:
        service:
          type: LoadBalancer