---
- name: Install containerd
  apt:
    name:
      - containerd
    state: latest

- name: Pause 30s
  pause:
    seconds: 30

- name: Create the containerd config directory
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create containerd config file
  file:
    path: /etc/containerd/config.toml
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Overwrite the content of a file
  copy:
    dest: /etc/containerd/config.toml
    content: |
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
          SystemdCgroup = true
    force: true

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted

- name: Ensure containerd service is started and enabled
  systemd:
    name: containerd
    enabled: true
    state: started
