---
- name: Create sysctl configuration file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.ipv4.ip_forward = 1
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl parameters without reboot
  command: sysctl --system

- name: Verify net.ipv4.ip_forward is set to 1
  command: sysctl net.ipv4.ip_forward
  register: sysctl_output

- name: Ensure net.ipv4.ip_forward is set to 1
  assert:
    that:
      - sysctl_output.stdout == 'net.ipv4.ip_forward = 1'
    success_msg: "net.ipv4.ip_forward is correctly set to 1."
    fail_msg: "net.ipv4.ip_forward is not set to 1."

- name: Disable all swap
  command: swapoff -a
