apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: "Infra-level applications (cert-manager, external-secrets, storage, etc.)"

  # Which Git/Helm repos Apps in this project may use
  sourceRepos:
    - https://charts.jetstack.io
    - https://github.com/rancher/local-path-provisioner.git
    - https://charts.external-secrets.io
    - https://github.com/external-secrets/external-secrets.git
    - https://github.com/przemekgorzynski/k8s.git

  # Allowed deployment targets (namespaces & clusters)
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: local-path-storage
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc


  # ALLOW these cluster-scoped resources:
  clusterResourceWhitelist:
    # Namespaces
    - group: ""
      kind: Namespace

    # CRDs & Webhooks
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration

    # StorageClasses
    - group: storage.k8s.io
      kind: StorageClass

    # Cluster-level RBAC
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

    # Namespaced RBAC (for leader-election in kube-system)
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    
    - group: external-secrets.io
      kind: ClusterSecretStore

