# kustomization.yml
namespace: metallb-system

resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
  - L2Advertisement.yml
  - IPAddressPool.yml
  - ServiceAccount_metalLB.yml
  # - CronJob_patch_metalLB_IP.yml

labels:
  - includeSelectors: true
    pairs:
      app: metallb

namespace: metallb-system