apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cronjob-ip-update-role
rules:
- apiGroups: ["metallb.io"]
  resources: ["ipaddresspools"]
  verbs: ["patch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjob-ip-update-role-binding
subjects:
- kind: ServiceAccount
  name: cronjob-service-account
roleRef:
  kind: Role
  name: cronjob-ip-update-role
  apiGroup: rbac.authorization.k8s.io

