apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nginx_deployment.yml
- nginx_service.yml

# Kustomization needs to be made
labels:
  - includeSelectors: true
    pairs:
      app: nginx
