---
all:
  vars:
    ansible_user: przemek
    standard_packages:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - curl
      - network-manager
      - git
      - net-tools
      - vim
      - wget
      - gpg
      - gnupg2
    packages_to_remove:
      - apparmor
    k8s_pkgs:
      - kubelet
      - kubeadm
      - kubectl
    k8s_token: b0r7b8.8d1728519297d79c
    hosts_arch: arm64

  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    controlPlane:
      hosts:
        k8s-master:
          ansible_host: 10.0.0.100
          kube_version: "v1.31.0"
          service_cidr: "10.96.0.0/12"
          pod_network_cidr: "10.244.0.0/16"
          kubeadmin_config: /etc/kubernetes/admin.conf
          enable_dashboard: false
          crd:
            - name: metallb
              url: https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
              present: true
    nodes:
      hosts:
        k8s-node01:
          ansible_host: 10.0.0.101
