---
all:
  vars:
    ubuntu_codename: jammy # 22.04 LTS
    ansible_user: przemek
    standard_packages:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - curl
      - network-manager
      - git
      - net-tools
      - vim
      - wget
      - gpg
    k8s_pkgs:
      - kubelet
      - kubeadm
      - kubectl

  hosts:
    master:
      ansible_host: 10.0.0.100
    node1:
      ansible_host: 10.0.0.101
