apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yml
- nginx_deployment.yml
- nginx_service.yml

replicas:
  - name: nginx-deployment
    count: 1

labels:
  - includeSelectors: true
    pairs:
      app: nginx

namespace: nginx
