
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- metallb/
- nginx_ingress/
- nginx/

# Kustomization needs to be made
labels:
  - includeSelectors: true
    pairs:
      project: GorillaBay
