---
- name: Install containerd
  apt:
    name: containerd
    state: latest

- name: Create the containerd config directory
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create containerd config file
  file:
    path: /etc/containerd/config.toml
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Generate containerd default config and save to /etc/containerd/config.toml
  command: >
    bash -c "containerd config default | tee /etc/containerd/config.toml"

- name: Ensure SystemdCgroup is set to true in /etc/containerd/config.toml
  replace:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted

- name: Ensure containerd service is started and enabled
  systemd:
    name: containerd
    enabled: true
    state: started
