---
- name: Enable cgroup in /boot/firmware/cmdline.txt
  shell: |
    cgroup="$(head -n1 /boot/firmware/cmdline.txt) cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"
    echo $cgroup | sudo tee /boot/firmware/cmdline.txt

- name: Create /etc/modules-load.d/k8s.conf file with required modules
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Modify sysctl configuration file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    owner: root
    group: root
    mode: '0644'

- name: modprobe overlay
  ansible.builtin.command: modprobe overlay

- name: modprobe br_netfilter
  ansible.builtin.command: modprobe br_netfilter

- name: Apply sysctl parameters without reboot
  command: sysctl --system

- name: Disable all swap
  command: swapoff -a

- name: Comment out swap entry in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^\s*[^#]\s*swap\s+'
    line: '#\g<0>'
    backrefs: yes

